Writable:
  LogLevel: INFO

Service:
  Host: localhost
  Port: 59997
  StartupMsg: 'opcua device service started'

Device:
  DevicesDir: ./res/devices
  ProfilesDir: ./res/profiles

OPCUAServer:
  CertFile: ''
  KeyFile: ''
  ApplicationURI: ''
